; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower

[env:rpipico2w]
board = rpipico2w
lib_deps = 
	adafruit/Adafruit BME680 Library@^2.0.6
	stevemarple/MCP342x@^1.0.4
	adafruit/Adafruit SGP41@^1.0.1
	adafruit/Adafruit VEML7700 Library@^2.1.6
